apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "titan-iraksha.fullname" . }}
  labels:
    {{- include "titan-iraksha.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: 2
  #{{- end }}
  selector:
    matchLabels:
      {{- include "titan-iraksha.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "titan-iraksha.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "titan-iraksha.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HOST_IP
               valueFrom:
                 fieldRef:
                   apiVersion: v1
                   fieldPath: status.hostIP
            - name: AWS_XRAY_DAEMON_ADDRESS
              value: $(HOST_IP):2000
            - name: MYSQL_HOST
              value: "{{ .Values.secrets.dbhost }}"
            - name: MYSQL_PORT
              value: "{{ .Values.secrets.dbport }}"
            - name: MYSQL_DB
              value: "{{ .Values.secrets.dbname }}"
            - name: DB_USER
              value: "{{ .Values.secrets.dbuser }}"
            - name: DB_PASSWORD
              value: "{{ .Values.secrets.dbpass }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
              tcpSocket:
                 port: 8080
              initialDelaySeconds: 5
              periodSeconds: 10
          readinessProbe:
              tcpSocket:
                 port: 8080
              initialDelaySeconds: 5
              periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
